### ISSUE TITLE
怎样才能删除自己的账户?

### ISSUE THREAD

**Issue by PBnicad** [Itoktsnhc/stat.itok#37]
想要删除服务器上的账户
![image](https://github.com/Itoktsnhc/stat.itok/assets/36125594/008710e6-fb57-40bc-8037-5fa2c6e55bba)

**Comment by Itoktsnhc** [comment]
![image](https://github.com/Itoktsnhc/stat.itok/assets/11204672/f86be42e-929f-4bd0-9092-711ff59bf7d2)
取消所有的模式选择即可
