### ISSUE TITLE
How to stop stat.ink monitor

### ISSUE THREAD

**Issue by Cpaulyz** [Itoktsnhc/stat.itok#38]
Hi 

I've been using stat.itok for a while now, thanks for making a tool that has provided me with great convenience.

I recently saw an announcement from Nintendo. Nintendo's approach is too unfair.🥲  I am afraid there may be issues with my account and would like to temporarily stop using monitoring... But I don't see an action button for it on stat.itok, how can I stop stat.ink monitor? Thank you again for creating the stat.itok tool!!!

<img width="391" alt="image" src="https://github.com/Itoktsnhc/stat.itok/assets/43774645/f70343da-1722-4c11-be3b-d8f090752bb6">

**Comment by Itoktsnhc** [comment]
Hi, you can uncheck all your battle modes to disable stat.itok ‘s auto monitor. If you want to delete your Nintendo account info in stat.itok please email me your account id in the right-top corner of stat.itok .
***@***.***


Thanks
From: Chen ***@***.***>
Sent: Friday, September 15, 2023 15:33
To: ***@***.***>
Cc: ***@***.***>
Subject: [Itoktsnhc/stat.itok] How to stop stat.ink monitor (Issue #38)


Hi

I've been using stat.itok for a while now, thanks for making a tool that has provided me with great convenience.

I recently saw an announcement from Nintendo. Nintendo's approach is too unfair.🥲 I am afraid there may be issues with my account and would like to temporarily stop using monitoring... But I don't see an action button for it on stat.itok, how can I stop stat.ink monitor? Thank you again for creating the stat.itok tool!!!
[image]<https://user-images.githubusercontent.com/43774645/268207470-f70343da-1722-4c11-be3b-d8f090752bb6.png>
